import type { Kunde, Aufgabe, Anruf, Besuch, Angebot, Aktivitaet, Ansprechpartner } from "./types";

export const mockKunden: Kunde[] = [
  {
    id: "1",
    nummer: "K-10001",
    name1: "Müller & Söhne GmbH",
    name2: "Metallverarbeitung",
    strasse: "Industriestraße 42",
    plz: "40210",
    ort: "Düsseldorf",
    telefon: "+49 211 884 200",
    email: "info@mueller-soehne.de",
    branche: "Metallverarbeitung",
    status: "aktiv",
    letzte_aktivitaet: "2026-03-20",
    letzte_besuch: "2026-03-15",
    umsatz: 148500,
    created_at: "2024-01-10",
  },
  {
    id: "2",
    nummer: "K-10002",
    name1: "Schneider Logistik AG",
    strasse: "Hafenweg 17",
    plz: "45356",
    ort: "Essen",
    telefon: "+49 201 445 600",
    email: "kontakt@schneider-logistik.de",
    branche: "Logistik",
    status: "aktiv",
    letzte_aktivitaet: "2026-03-22",
    letzte_besuch: "2026-02-10",
    umsatz: 234800,
    created_at: "2024-02-15",
  },
  {
    id: "3",
    nummer: "K-10003",
    name1: "Weber Bau GmbH",
    name2: "Hoch- und Tiefbau",
    strasse: "Bahnhofstraße 8",
    plz: "50667",
    ort: "Köln",
    telefon: "+49 221 770 330",
    email: "office@weber-bau.de",
    branche: "Baugewerbe",
    status: "aktiv",
    letzte_aktivitaet: "2026-03-18",
    letzte_besuch: "2026-03-18",
    umsatz: 89200,
    created_at: "2024-03-01",
  },
  {
    id: "4",
    nummer: "K-10004",
    name1: "Fischer Elektronik KG",
    strasse: "Technologiepark 3",
    plz: "44227",
    ort: "Dortmund",
    telefon: "+49 231 995 100",
    email: "info@fischer-elektronik.de",
    branche: "Elektronik",
    status: "aktiv",
    letzte_aktivitaet: "2026-03-10",
    letzte_besuch: "2026-01-20",
    umsatz: 312000,
    created_at: "2024-04-12",
  },
  {
    id: "5",
    nummer: "K-10005",
    name1: "Wagner Automotive GmbH",
    strasse: "Motorstraße 55",
    plz: "41069",
    ort: "Mönchengladbach",
    telefon: "+49 2161 887 400",
    email: "verwaltung@wagner-auto.de",
    branche: "Automotive",
    status: "inaktiv",
    letzte_aktivitaet: "2025-11-15",
    letzte_besuch: "2025-10-05",
    umsatz: 67400,
    created_at: "2024-05-20",
  },
  {
    id: "6",
    nummer: "K-10006",
    name1: "Braun Textil AG",
    name2: "Workwear Division",
    strasse: "Textilstraße 22",
    plz: "42103",
    ort: "Wuppertal",
    telefon: "+49 202 556 200",
    email: "info@braun-textil.de",
    branche: "Textil",
    status: "aktiv",
    letzte_aktivitaet: "2026-03-24",
    letzte_besuch: "2026-03-22",
    umsatz: 178900,
    created_at: "2024-06-08",
  },
  {
    id: "7",
    nummer: "K-10007",
    name1: "Hoffmann Chemie GmbH",
    strasse: "Chemiepark Nord 1",
    plz: "47229",
    ort: "Duisburg",
    telefon: "+49 203 660 800",
    email: "kontakt@hoffmann-chemie.de",
    branche: "Chemie",
    status: "neu",
    letzte_aktivitaet: "2026-03-25",
    umsatz: 0,
    created_at: "2026-03-20",
  },
  {
    id: "8",
    nummer: "K-10008",
    name1: "Richter & Partner Consulting",
    strasse: "Königsallee 88",
    plz: "40212",
    ort: "Düsseldorf",
    telefon: "+49 211 338 900",
    email: "office@richter-consulting.de",
    branche: "Beratung",
    status: "aktiv",
    letzte_aktivitaet: "2026-03-21",
    letzte_besuch: "2026-03-01",
    umsatz: 425000,
    created_at: "2024-07-15",
  },
  {
    id: "9",
    nummer: "K-10009",
    name1: "Klein Lebensmittel GmbH",
    strasse: "Marktstraße 7",
    plz: "51063",
    ort: "Köln",
    telefon: "+49 221 447 200",
    email: "einkauf@klein-lebensmittel.de",
    branche: "Lebensmittel",
    status: "aktiv",
    letzte_aktivitaet: "2026-03-19",
    letzte_besuch: "2026-02-28",
    umsatz: 198600,
    created_at: "2024-08-01",
  },
  {
    id: "10",
    nummer: "K-10010",
    name1: "Zimmermann Pharma GmbH",
    strasse: "Pharmaweg 14",
    plz: "40789",
    ort: "Monheim am Rhein",
    telefon: "+49 2173 990 100",
    email: "info@zimmermann-pharma.de",
    branche: "Pharma",
    status: "aktiv",
    letzte_aktivitaet: "2026-03-23",
    letzte_besuch: "2026-03-10",
    umsatz: 567000,
    created_at: "2024-09-10",
  },
];

export const mockAufgaben: Aufgabe[] = [
  {
    id: "1",
    titel: "Angebot nachfassen",
    beschreibung: "Nachfassen bezüglich Angebot AN-2026-0045 – Chemikalienlieferung Q2",
    kunde_id: "7",
    kunde: mockKunden[6],
    zugewiesen_an: "user-1",
    zugewiesener_name: "Thomas Berger",
    erstellt_von: "user-1",
    status: "offen",
    prioritaet: "hoch",
    faellig_am: "2026-03-27",
    ereignis: "Nachfassen",
    created_at: "2026-03-20",
  },
  {
    id: "2",
    titel: "Kundenpräsentation vorbereiten",
    beschreibung: "Präsentation für das Quartalsgespräch mit Richter & Partner vorbereiten",
    kunde_id: "8",
    kunde: mockKunden[7],
    zugewiesen_an: "user-2",
    zugewiesener_name: "Sandra Koch",
    erstellt_von: "user-1",
    status: "in_bearbeitung",
    prioritaet: "hoch",
    faellig_am: "2026-03-28",
    ereignis: "Präsentation",
    created_at: "2026-03-18",
  },
  {
    id: "3",
    titel: "Vertrag verlängern",
    beschreibung: "Jahresvertrag mit Braun Textil AG verlängern – läuft am 30.04. aus",
    kunde_id: "6",
    kunde: mockKunden[5],
    zugewiesen_an: "user-1",
    zugewiesener_name: "Thomas Berger",
    erstellt_von: "user-1",
    status: "offen",
    prioritaet: "mittel",
    faellig_am: "2026-04-15",
    ereignis: "Vertrag",
    created_at: "2026-03-15",
  },
  {
    id: "4",
    titel: "Reklamation bearbeiten",
    beschreibung: "Beschädigte Lieferung von Müller & Söhne klären und Gutschrift erstellen",
    kunde_id: "1",
    kunde: mockKunden[0],
    zugewiesen_an: "user-3",
    zugewiesener_name: "Jan Hofmann",
    erstellt_von: "user-2",
    status: "in_bearbeitung",
    prioritaet: "hoch",
    faellig_am: "2026-03-26",
    ereignis: "Reklamation",
    created_at: "2026-03-22",
  },
  {
    id: "5",
    titel: "Katalog zusenden",
    beschreibung: "Neuen Produktkatalog 2026 an Weber Bau GmbH senden",
    kunde_id: "3",
    kunde: mockKunden[2],
    zugewiesen_an: "user-2",
    zugewiesener_name: "Sandra Koch",
    erstellt_von: "user-1",
    status: "erledigt",
    prioritaet: "niedrig",
    faellig_am: "2026-03-20",
    erledigt_am: "2026-03-19T14:30:00",
    ereignis: "Versand",
    created_at: "2026-03-12",
  },
  {
    id: "6",
    titel: "Preisliste aktualisieren",
    beschreibung: "Aktuelle Preisliste für Schneider Logistik AG zusammenstellen",
    kunde_id: "2",
    kunde: mockKunden[1],
    zugewiesen_an: "user-1",
    zugewiesener_name: "Thomas Berger",
    erstellt_von: "user-1",
    status: "offen",
    prioritaet: "mittel",
    faellig_am: "2026-04-02",
    ereignis: "Preisliste",
    created_at: "2026-03-24",
  },
  {
    id: "7",
    titel: "Onboarding abschließen",
    beschreibung: "Onboarding-Prozess für Neukunden Hoffmann Chemie abschließen",
    kunde_id: "7",
    kunde: mockKunden[6],
    zugewiesen_an: "user-3",
    zugewiesener_name: "Jan Hofmann",
    erstellt_von: "user-1",
    status: "in_bearbeitung",
    prioritaet: "hoch",
    faellig_am: "2026-03-30",
    ereignis: "Onboarding",
    created_at: "2026-03-20",
  },
  {
    id: "8",
    titel: "Jahresabschluss-Meeting",
    beschreibung: "Jahresabschluss-Meeting mit Zimmermann Pharma GmbH koordinieren",
    kunde_id: "10",
    kunde: mockKunden[9],
    zugewiesen_an: "user-2",
    zugewiesener_name: "Sandra Koch",
    erstellt_von: "user-2",
    status: "erledigt",
    prioritaet: "mittel",
    faellig_am: "2026-03-25",
    erledigt_am: "2026-03-25T10:00:00",
    ereignis: "Meeting",
    created_at: "2026-03-10",
  },
];

export const mockAnrufe: Anruf[] = [
  {
    id: "1",
    kunde_id: "5",
    kunde: mockKunden[4],
    mitarbeiter_id: "user-1",
    mitarbeiter_name: "Thomas Berger",
    faellig_am: "2026-03-26",
    notizen: "Reaktivierungsgespräch – letzter Kontakt vor 4 Monaten",
    status: "offen",
    created_at: "2026-03-20",
  },
  {
    id: "2",
    kunde_id: "4",
    kunde: mockKunden[3],
    mitarbeiter_id: "user-2",
    mitarbeiter_name: "Sandra Koch",
    faellig_am: "2026-03-26",
    notizen: "Rückruf wegen technischer Fragen zur Bestellung",
    status: "offen",
    created_at: "2026-03-21",
  },
  {
    id: "3",
    kunde_id: "9",
    kunde: mockKunden[8],
    mitarbeiter_id: "user-3",
    mitarbeiter_name: "Jan Hofmann",
    faellig_am: "2026-03-27",
    notizen: "Terminvereinbarung für Besuch April",
    status: "offen",
    created_at: "2026-03-22",
  },
  {
    id: "4",
    kunde_id: "1",
    kunde: mockKunden[0],
    mitarbeiter_id: "user-1",
    mitarbeiter_name: "Thomas Berger",
    faellig_am: "2026-03-25",
    durchgefuehrt_am: "2026-03-25T09:15:00",
    notizen: "Gutschrift bestätigt, Kunde zufrieden",
    status: "erledigt",
    created_at: "2026-03-22",
  },
  {
    id: "5",
    kunde_id: "2",
    kunde: mockKunden[1],
    mitarbeiter_id: "user-2",
    mitarbeiter_name: "Sandra Koch",
    faellig_am: "2026-03-28",
    notizen: "Nachfassen wegen Rahmenvertrag Q2",
    status: "offen",
    created_at: "2026-03-24",
  },
  {
    id: "6",
    kunde_id: "7",
    kunde: mockKunden[6],
    mitarbeiter_id: "user-1",
    mitarbeiter_name: "Thomas Berger",
    faellig_am: "2026-03-28",
    notizen: "Erstgespräch nach Onboarding",
    status: "offen",
    created_at: "2026-03-25",
  },
];

export const mockBesuche: Besuch[] = [
  {
    id: "1",
    kunde_id: "4",
    kunde: mockKunden[3],
    mitarbeiter_id: "user-2",
    mitarbeiter_name: "Sandra Koch",
    faellig_am: "2026-03-27",
    notizen: "Jahresgespräch Q1 – Produktpräsentation neue Linie",
    uhrzeit_von: "09:30",
    uhrzeit_bis: "11:00",
    status: "offen",
    created_at: "2026-03-20",
  },
  {
    id: "2",
    kunde_id: "9",
    kunde: mockKunden[8],
    mitarbeiter_id: "user-3",
    mitarbeiter_name: "Jan Hofmann",
    faellig_am: "2026-04-03",
    notizen: "Tour Köln – Routenbesuch",
    status: "offen",
    created_at: "2026-03-22",
  },
  {
    id: "3",
    kunde_id: "6",
    kunde: mockKunden[5],
    mitarbeiter_id: "user-1",
    mitarbeiter_name: "Thomas Berger",
    faellig_am: "2026-03-22",
    durchgefuehrt_am: "2026-03-22T13:00:00",
    notizen: "Vertragsverhandlung gut verlaufen – Abschluss wahrscheinlich",
    uhrzeit_von: "10:00",
    uhrzeit_bis: "11:15",
    bericht: "Jahresgespräch verlief positiv. Kunde zeigte starkes Interesse an der neuen Produktlinie. Preisverhandlung für Q2-Rahmenvertrag begonnen. Nächster Schritt: Angebot bis 15.04. einreichen.",
    dauer_minuten: 75,
    status: "erledigt",
    created_at: "2026-03-10",
  },
  {
    id: "4",
    kunde_id: "10",
    kunde: mockKunden[9],
    mitarbeiter_id: "user-2",
    mitarbeiter_name: "Sandra Koch",
    faellig_am: "2026-04-10",
    notizen: "Halbjahresgespräch – Umsatzentwicklung besprechen",
    status: "offen",
    created_at: "2026-03-24",
  },
  {
    id: "5",
    kunde_id: "8",
    kunde: mockKunden[7],
    mitarbeiter_id: "user-1",
    mitarbeiter_name: "Thomas Berger",
    faellig_am: "2026-03-29",
    notizen: "Abschlusspräsentation Consulting-Projekt",
    status: "offen",
    created_at: "2026-03-21",
  },
];

export const mockAngebote: Angebot[] = [
  {
    id: "1",
    nummer: "AN-2026-0051",
    kunde_id: "10",
    kunde: mockKunden[9],
    artikel: "Laborausstattung Komplett-Set Pro",
    menge: 2,
    einzelpreis: 18500,
    gesamtpreis: 37000,
    status: "in_verhandlung",
    erstellt_am: "2026-03-15",
    created_at: "2026-03-15",
  },
  {
    id: "2",
    nummer: "AN-2026-0050",
    kunde_id: "8",
    kunde: mockKunden[7],
    artikel: "CRM-Implementierung Enterprise",
    menge: 1,
    einzelpreis: 45000,
    gesamtpreis: 45000,
    status: "offen",
    erstellt_am: "2026-03-18",
    created_at: "2026-03-18",
  },
  {
    id: "3",
    nummer: "AN-2026-0049",
    kunde_id: "6",
    kunde: mockKunden[5],
    artikel: "Schutzausrüstung Jahrespaket 2026",
    menge: 500,
    einzelpreis: 89,
    gesamtpreis: 44500,
    status: "angenommen",
    erstellt_am: "2026-03-10",
    created_at: "2026-03-10",
  },
  {
    id: "4",
    nummer: "AN-2026-0048",
    kunde_id: "4",
    kunde: mockKunden[3],
    artikel: "Elektronik-Komponenten Rahmenvertrag",
    menge: 1000,
    einzelpreis: 245,
    gesamtpreis: 245000,
    status: "in_verhandlung",
    erstellt_am: "2026-03-08",
    created_at: "2026-03-08",
  },
  {
    id: "5",
    nummer: "AN-2026-0047",
    kunde_id: "2",
    kunde: mockKunden[1],
    artikel: "Transportmanagementsystem Basic",
    menge: 1,
    einzelpreis: 12800,
    gesamtpreis: 12800,
    status: "abgelehnt",
    erstellt_am: "2026-03-01",
    created_at: "2026-03-01",
  },
  {
    id: "6",
    nummer: "AN-2026-0046",
    kunde_id: "3",
    kunde: mockKunden[2],
    artikel: "Baustofflieferung Projekt Köln-Ehrenfeld",
    menge: 800,
    einzelpreis: 56,
    gesamtpreis: 44800,
    status: "angenommen",
    erstellt_am: "2026-02-28",
    created_at: "2026-02-28",
  },
  {
    id: "7",
    nummer: "AN-2026-0045",
    kunde_id: "7",
    kunde: mockKunden[6],
    artikel: "Chemikalien-Lieferpaket Q2",
    menge: 50,
    einzelpreis: 1200,
    gesamtpreis: 60000,
    status: "offen",
    erstellt_am: "2026-03-20",
    created_at: "2026-03-20",
  },
];

export const mockAktivitaeten: Aktivitaet[] = [
  {
    id: "1",
    kunde_id: "6",
    typ: "besuch",
    beschreibung: "Besuch bei Braun Textil AG – Vertragsverhandlung",
    mitarbeiter_id: "user-1",
    mitarbeiter_name: "Thomas Berger",
    created_at: "2026-03-22T13:00:00",
  },
  {
    id: "2",
    kunde_id: "1",
    typ: "anruf",
    beschreibung: "Rückruf Müller & Söhne – Gutschrift bestätigt",
    mitarbeiter_id: "user-1",
    mitarbeiter_name: "Thomas Berger",
    created_at: "2026-03-25T09:15:00",
  },
  {
    id: "3",
    kunde_id: "7",
    typ: "notiz",
    beschreibung: "Neukunde Hoffmann Chemie – Ersterfassung abgeschlossen",
    mitarbeiter_id: "user-3",
    mitarbeiter_name: "Jan Hofmann",
    created_at: "2026-03-25T11:30:00",
  },
  {
    id: "4",
    kunde_id: "10",
    typ: "angebot",
    beschreibung: "Angebot AN-2026-0051 erstellt – Laborausstattung",
    mitarbeiter_id: "user-2",
    mitarbeiter_name: "Sandra Koch",
    created_at: "2026-03-24T15:00:00",
  },
  {
    id: "5",
    kunde_id: "8",
    typ: "aufgabe",
    beschreibung: "Aufgabe 'Jahresabschluss-Meeting' erledigt",
    mitarbeiter_id: "user-2",
    mitarbeiter_name: "Sandra Koch",
    created_at: "2026-03-25T10:00:00",
  },
  {
    id: "6",
    kunde_id: "3",
    typ: "angebot",
    beschreibung: "Angebot AN-2026-0046 angenommen – Baustofflieferung",
    mitarbeiter_id: "user-3",
    mitarbeiter_name: "Jan Hofmann",
    created_at: "2026-03-23T09:00:00",
  },
];

export const mockWochenchart = [
  { tag: "Mo", kontakte: 8 },
  { tag: "Di", kontakte: 12 },
  { tag: "Mi", kontakte: 7 },
  { tag: "Do", kontakte: 15 },
  { tag: "Fr", kontakte: 11 },
  { tag: "Sa", kontakte: 4 },
  { tag: "So", kontakte: 2 },
];

export const mockUmsatzChart = [
  { monat: "Jan", umsatz: 185000 },
  { monat: "Feb", umsatz: 220000 },
  { monat: "Mär", umsatz: 198000 },
  { monat: "Apr", umsatz: 265000 },
  { monat: "Mai", umsatz: 241000 },
  { monat: "Jun", umsatz: 290000 },
  { monat: "Jul", umsatz: 318000 },
  { monat: "Aug", umsatz: 275000 },
  { monat: "Sep", umsatz: 342000 },
  { monat: "Okt", umsatz: 310000 },
  { monat: "Nov", umsatz: 358000 },
  { monat: "Dez", umsatz: 425000 },
];

export const mockMitarbeiterStats = [
  { name: "Thomas Berger", anrufe: 28, besuche: 12 },
  { name: "Sandra Koch", anrufe: 35, besuche: 18 },
  { name: "Jan Hofmann", anrufe: 22, besuche: 9 },
  { name: "Maria Schulz", anrufe: 41, besuche: 15 },
];

export const mockAnsprechpartner: Ansprechpartner[] = [
  {
    id: "ap-1",
    kunde_id: "1", // Müller & Söhne GmbH
    name: "Hans Müller",
    position: "Geschäftsführer",
    telefon: "+49 211 884 201",
    email: "h.mueller@mueller-soehne.de",
    created_at: "2026-01-10T09:00:00Z",
  },
  {
    id: "ap-2",
    kunde_id: "1", // Müller & Söhne GmbH
    name: "Petra Bauer",
    position: "Einkaufsleiterin",
    telefon: "+49 211 884 202",
    email: "p.bauer@mueller-soehne.de",
    created_at: "2026-01-10T09:05:00Z",
  },
  {
    id: "ap-3",
    kunde_id: "4", // Fischer Elektronik KG
    name: "Klaus Fischer",
    position: "Inhaber",
    telefon: "+49 231 995 101",
    email: "k.fischer@fischer-elektronik.de",
    created_at: "2026-01-15T10:00:00Z",
  },
  {
    id: "ap-4",
    kunde_id: "4", // Fischer Elektronik KG
    name: "Sabine Krause",
    position: "Technische Leiterin",
    telefon: "+49 231 995 102",
    email: "s.krause@fischer-elektronik.de",
    created_at: "2026-01-15T10:10:00Z",
  },
];
